[package]
name = "ipaddr-from-str"
version = "0.1.0"
authors = ["jgerber <jlgerber@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"
dns-lookup = "1.0.1"
lazy_static = "1.4.0"
